import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProductCard from "../components/ProductCard";
import Layout from "../layouts/Layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full">
          <ProductCard
            name={"Product 1"}
            price={0}
            colorFamily={{
              name: "red",
            }}
            thumbnailImage={{
              file: {
                alt: "alt",
                url: "",
              },
            }}
            categoryTags={[]}
            shopifyProductEu={{
              variants: {
                edges: [
                  {
                    node: {
                      price: 0,
                    },
                  },
                ],
              },
            }}
          />
          <ProductCard
            name={"Product 2"}
            price={0}
            colorFamily={{
              name: "red",
            }}
            thumbnailImage={{
              file: {
                alt: "alt",
                url: "",
              },
            }}
            categoryTags={[]}
            shopifyProductEu={{
              variants: {
                edges: [
                  {
                    node: {
                      price: 0,
                    },
                  },
                ],
              },
            }}
          />
          <ProductCard
            name={"Product 3"}
            price={0}
            colorFamily={{
              name: "red",
            }}
            thumbnailImage={{
              file: {
                alt: "alt",
                url: "",
              },
            }}
            categoryTags={[]}
            shopifyProductEu={{
              variants: {
                edges: [
                  {
                    node: {
                      price: 0,
                    },
                  },
                ],
              },
            }}
          />
        </section>
      </Layout>
    </div>
  );
};

export default Home;
