import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../layouts/Layout";
import CategoryFilter from "../components/Filters/CategoryFilter";
import Page from "../components/Page";
import Header from "../layouts/Header";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  const getQueryUrl = () => {
    const { query } = router;
    let page = Number(query.page) >= 1 ? Number(query.page) : 1;
    let limit = Number(query.limit) >= 10 ? Number(query.limit) : 10;
    let search = query.search || "";

    return {
      router,
      page,
      limit,
      search,
    };
  };

  const { page, limit, search } = getQueryUrl();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

        <Header />

        <section>
          <Page page={page} limit={limit} search={search} />
          {/* <ProductList productData={data} /> */}
          {/* {data.map((product) => (
            <ProductCard product={product} />
          ))} */}

          {/* <ProductCard
            name={"Product 1"}
            price={0}
            colorFamily={{
              name: "red",
            }}
            thumbnailImage={{
              file: {
                alt: "alt",
                url: "",
              },
            }}
            categoryTags={[]}
            shopifyProductEu={{
              variants: {
                edges: [
                  {
                    node: {
                      price: 0,
                    },
                  },
                ],
              },
            }}
          /> */}
        </section>
      </Layout>
    </div>
  );
};

export default Home;
