import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../layouts/Layout";
import Page from "../components/Page";
import Header from "../layouts/Header";
import useGetQueryUrl from "../lib/useGetQueryUrl";

const Home: NextPage = () => {
  const { page, limit, offset } = useGetQueryUrl();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header />
        <section>
          <div style={{ display: "none" }}>
            <Page
              page={page - 1}
              limit={limit}
              offset={offset}
            />
          </div>

          <Page
            page={page}
            limit={limit}
            offset={offset}
          />

          <div style={{ display: "none" }}>
            <Page
              page={page + 1}
              limit={limit}
              offset={offset}
            />
          </div>
        </section>
      </Layout>
    </div>
  );
};

export default Home;
